### ISSUE TITLE
Is this an exposed secret?

### ISSUE THREAD

**Issue by diginicho** [go-openapi/spec#167] opened 2023-09-15 17:42 UTC
https://github.com/go-openapi/spec/blob/832384d4ee1b2aa2479009d732f42866b63ed5f6/appveyor.yml#L24C1-L29C18

**Comment by masv3971** [comment] 2023-10-19 06:20
I got the same warning.

**Comment by fredbi** [comment] 2023-11-30 12:04
Duplicate of #161 . This is being covered.

**Closed** 2023-12-01 05:28 UTC
Labels: duplicate, pending PR
