### ISSUE TITLE
Temporary files are not deleted on program termination

### ISSUE THREAD

**Issue by sebastien-rosset** [go-openapi/spec#47] opened 2017-12-19 01:54 UTC
The ExpandSchema() method calls ioutil.TempFile(), which creates a temporary file, and the file is not deleted before program termination. As specified in the golang documentation, it is the caller's responsibility to delete temporary files created by ioutil.TempFile()

https://github.com/go-openapi/spec/blob/aa90e7cfc0a78736511f9eeab8f7586d98c8f53a/expander.go#L534

As a specific use case, ExpandSchema() is called by "swagger validate" to validate swagger spec files. Every invocation of "swagger validate" may end up creating multiple temporary files in the temp folder (e.g. /tmp for Linux). A workaround would be to delete the /tmp/root* files after execution, but this can be difficult in a CICD environment where many builds are invoked concurrently.

Here is a stack trace of running swagger validate under dlv. A **/tmp/root491780128** temporary file is created, and the file is not deleted before program termination.

It looks like there is a missing call to defer os.Remove(file.Name()) in the ExpandSchema() method.

```
(dlv) bt
 0  0x00000000004c2388 in os.OpenFile
    at /usr/local/go/src/os/file_unix.go:147
 1  0x000000000057445a in io/ioutil.TempFile
    at /usr/local/go/src/io/ioutil/tempfile.go:55
 2  0x0000000000869953 in github.com/go-swagger/go-swagger/vendor/github.com/go-openapi/spec.ExpandSchema
    at ./vendor/github.com/go-openapi/spec/expander.go:534
 3  0x0000000000a8c25b in github.com/go-swagger/go-swagger/vendor/github.com/go-openapi/validate.NewSchemaValidator
    at ./vendor/github.com/go-openapi/validate/schema.go:53
 4  0x0000000000a9271a in github.com/go-swagger/go-swagger/vendor/github.com/go-openapi/validate.(*SpecValidator).Validate
    at ./vendor/github.com/go-openapi/validate/spec.go:103
 5  0x0000000000a92342 in github.com/go-swagger/go-swagger/vendor/github.com/go-openapi/validate.Spec
    at ./vendor/github.com/go-openapi/validate/spec.go:51
 6  0x0000000000ca6e77 in github.com/go-swagger/go-swagger/cmd/swagger/commands.(*ValidateSpec).Execute
    at ./cmd/swagger/commands/validate.go:46
 7  0x00000000009562a7 in github.com/go-swagger/go-swagger/vendor/github.com/jessevdk/go-flags.(*Parser).ParseArgs
    at ./vendor/github.com/jessevdk/go-flags/parser.go:316
 8  0x0000000000955481 in github.com/go-swagger/go-swagger/vendor/github.com/jessevdk/go-flags.(*Parser).Parse
    at ./vendor/github.com/jessevdk/go-flags/parser.go:186
 9  0x0000000000ca9f41 in main.main
    at ./cmd/swagger/swagger.go:125
10  0x00000000004310e4 in runtime.main
    at /usr/local/go/src/runtime/proc.go:195
(dlv) print name
"/tmp/root491780128"

**Comment by fredbi** [comment] 2017-12-19 17:39
I've seen a PR has been merged today on this.
It looks like it introduced a regression.
Tests in go-openapi/validate that use to pass before now stumble on a panic().

Could it be possibly related?
```
=== RUN   TestJSONSchemaSuite
--- FAIL: TestJSONSchemaSuite (2.19s)
	type_test.go:147: Running additionalItems
	type_test.go:147: Running additionalProperties
	type_test.go:147: Running allOf
	type_test.go:147: Running anyOf
	type_test.go:147: Running default
	type_test.go:147: Running definitions
	type_test.go:147: Running dependencies
	type_test.go:147: Running enum
	type_test.go:147: Running format
	type_test.go:147: Running items
	type_test.go:147: Running maxItems
	type_test.go:147: Running maxLength
	type_test.go:147: Running maxProperties
	type_test.go:147: Running maximum
	type_test.go:147: Running minItems
	type_test.go:147: Running minLength
	type_test.go:147: Running minProperties
	type_test.go:147: Running minimum
	type_test.go:147: Running multipleOf
	type_test.go:147: Running not
	type_test.go:147: Running oneOf
	type_test.go:147: Running pattern
	type_test.go:147: Running patternProperties
	type_test.go:147: Running properties
	type_test.go:147: Running ref
panic: open /tmp/root104116106: no such file or directory [recovered]
	panic: open /tmp/root104116106: no such file or directory

goroutine 56 [running]:
panic(0x946480, 0xc42194eff0)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/panic.go:500 +0x1ae
testing.tRunner.func1(0xc421ccd2c0)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:579 +0x474
panic(0x946480, 0xc42194eff0)
	/home/travis/.gimme/ver
```

**Comment by casualjim** [comment] 2017-12-19 17:41
i reverted the PR

**Comment by fredbi** [comment] 2017-12-19 17:47
Ok I try again and bump my PR to validate

**Comment by fredbi** [comment] 2017-12-19 17:55
It passed the test now like before.

**Comment by sebastien-rosset** [comment] 2017-12-19 18:18
So go-openapi/validate reads the temporary files that have been created by go-openapi/spec? We still need to delete files before program termination.

**Comment by fredbi** [comment] 2017-12-19 18:23
There is no explicit access to these files in go-openapi/validate: just use spec methods.
I believe it's more a race condition created by the go test -race 
As you see, the broken test is on a ref testcase from the standard JSON-schema-test-suite

**Comment by fredbi** [comment] 2017-12-19 18:26
Don't know if it would help, but what I have changed on the validate side is that I try now to continue checking even though we know there are some errors.
Normally, severe errors (like unresolved references) have been tested to carefully avoid calling spec on invalid objects (same deal with analysis).

**Closed** 2017-12-19 19:54 UTC
Labels: enhancement
